{
    "openapi":"3.0.2",
    "info": {
      "title":"API Title",
      "version":"2.0",
      "description":"OpenAPI for Todolist RESTful API",
      "termsOfService": "https://www.programmerzamannow.com",
      "contact": {
        "name": "Kanza Az Zahrawani",
        "email": "kanza.az.zahrawani28@gmail.com",
        "url": "https:www.programmer.zaman.now"
    },

    "license":{
        "name": "APACHE 2.0",
        "url":"https://www.apache.org/licenses/LICENSE-2.0"
    }

    },
    "servers": [
      {
        "description": "Todolist RESTful API Server",
        "url": "https://{environment}.programmerzamannow.com",
        "variables": {
          "environment":{
            "default": "dev",
            "environment":"Server Environment",
            "enum": [
              "dev",
              "qa",
              "prod"
            ]
          }
        }
      }
    ],
"externalDocs": {
  "description": "Youtube Programmer Zaman Now",
  "url": "https://www.Youtube.com/ProgrammerZamanNow"
},

    "paths": {
      "/todolist":{
        "get":{
          "tags": ["todolist"],
          "summary": "get all todolist",
          "description": "get all todolist active by default",
          "responses": {
            "200":{
              "description": "Succes get all todolist",
              "content": {
                "application/json":{
                  "schema":{
                    "$ref": "#/components/schemas/arrayTodolist"
                  },
                  "examples": {
                    "succes":{
                      "description": "Example succes get all todolist",
                      "value":[
                        {
                          "id":"1",
                          "name":"Java",
                          "priority":3,
                          "tags":[
                            "Java","programming"
                          ]
                        },
                         {
                          "id":"2",
                          "name":"PHP",
                          "priority":5,
                          "tags":[
                            "PHP","web programming"
                          ]
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "parameters": [
            {
              "name": "include done",
              "in": "query",
              "required": false,
              "description": " is include done todolist",
              "schema":{
                "type": "boolean",
                "nullable": true
              }
            },
            {
              "name": "name",
              "in": "query",
              "required": false,
              "description": "Filter todolist by name",
              "schema":{
                "type": "string",
                "nullable": true,
                "minLength": 1,
                "maxLength": 100
              },
              "examples": {
                "java":{
                  "description": "Example name java",
                  "value":"Java"
                },
                "php":{
                  "description": "Example name PHP",
                  "value" :"PHP "
                }
              }
            }
          ]

        },
        "post":{
          "tags": ["todolist"],
          "summary": "Create new todolist",
          "description": "Create new todolist databases",
          "responses": {
            "200":{
              "description": "Succes create todolist",
              "content": {
                "application/json":{
                  "schema":{
                    "$ref": "#/components/schemas/todolist"
                  },
                  "examples": {
                    "java":{
                      "description": "Succes create java todolist",
                      "value":{
                        "id":"1",
                        "name":"Java",
                        "priority":3,
                        "tags":[
                          "Java","Programming"
                        ]
                      }
                    },
                    "PHP":{
                      "description": "Succes create PHP todolist",
                      "value":{
                          "id":"2",
                          "name":"PHP",
                          "priority":5,
                          "tags":[
                            "PHP","web programming"
                          ]
                      }
                    }

                  }
                }
              }
            }

          },
          "requestBody":{
            "required": true,
            "content": {
              "application/json":{
                "schema":{
                  "$ref": "#/components/schemas/createOrUpdateTodolist"
                },
                "examples": {
                  "java":{
                    "description": "Example Create todolist java",
                    "value":{
                      "name":"Java",
                      "priority":"3",
                      "tags":[
                        "Java",
                        "programming"
                      ]
                    }
                  },
                  "php":{
                    "description": "Example Create todolist PHP",
                    "value":{
                      "name":"PHP",
                      "priority":"3",
                      "tags":[
                        "PHP",
                        "web programming"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/todolist/{todolistId}":{
        "put":{
          "summary": "update existing todolist",
          "description": "Update existing todolist indatabases",
          "responses": {
"200":{
              "description": "Succes update todolist",
              "content": {
                "application/json":{
                  "schema":{
                   "$ref": "#/components/schemas/todolist"
                  },
                  "examples": {
                    "java":{
                      "description": "Succes create java todolist",
                      "value":{
                        "id":"1",
                        "name":"Java",
                        "priority":3,
                        "tags":[
                          "Java","Programming"
                        ]
                      }
                    },
                    "PHP":{
                      "description": "Succes update PHP todolist",
                      "value":{
                          "id":"2",
                          "name":"PHP",
                          "priority":5,
                          "tags":[
                            "PHP","web programming"
                          ]
                      }
                    }

                  }
                }
              }
            }
          },
          "parameters": [
            {
             "$ref": "#/components/parameters/TodolistId"
            }
          ],
          "requestBody":{
            "required": true,
            "content": {
              "application/json":{
                "schema":{
                 "$ref": "#/components/schemas/createOrUpdateTodolist"
                },
                "examples": {
                  "java":{
                    "description": "Example Create todolist java",
                    "value":{
                      "name":"Java",
                      "priority":"3",
                      "tags":[
                        "Java",
                        "programming"
                      ]
                    }
                  },
                  "php":{
                    "description": "Example Create todolist PHP",
                    "value":{
                      "name":"PHP",
                      "priority":"3",
                      "tags":[
                        "PHP",
                        "web programming"
                      ]
                    }
                  }
                }
              }
            }
          }

        },
        "delete":{
          "summary": "Delete existing todolist",
          "description": "Delete existing todolist in databases",
          "responses": { 
            "200":{
              "description": "Succes delete todolist",
              "content": {
                "application/json":{
                  "schema":{
                    "type": "object",
                    "properties": {
                      "succes":{
                        "type": "boolean"
                      }
                    }
                  },
                  "examples": {
                    "succes":{
                      "description": "succes delete todolist",
                      "value":{
                        "succes":true
                      }
                    }
                  }
                }
              }
            }, "404":{
              "description": "failed delete not found todolist",
              "content": {
                "application/json":{
                  "schema":{
                    "type": "object",
                    "properties": {
                      "succes":{
                        "type": "boolean"
                      }
                    }
                  },
                  "examples": {
                    "failed":{
                      "description": "failed delete todolist",
                      "value":{
                        "succes":false
                      }
                    }
                  }
                }
              }
            }

          },
          "parameters": [
            {
              "$ref": "#/components/parameters/TodolistId"
            }
          ]

        }
      }
    },
    "components": {
      "schemas": {
        
        "todolist":{

                "type": "object",
                  "properties": {
                    "id":{
                      "type": "string"
                    },
                    "name":{
                      "type": "string",
                      "minLength": 1,
                      "required": true
                    },
                    "priority":{
                      "type": "integer",
                      "format": "int32",
                      "default":1,
                      "required": true
                    },
                    "tags":{
                      "type": "array",
                      "required": false,
                      "minItems": 1,
                      "items":{
                        "type": "string",
                        "minLength": 1
                      }
                    }

        }
      },
      "createOrUpdateTodolist":{
        "type": "object",
                  "properties": {
                    "name":{
                      "type": "string",
                      "minLength": 1,
                      "required": true
                    },
                    "priority":{
                      "type": "integer",
                      "format": "int32",
                      "default":1,
                      "required": true
                    },
                    "tags":{
                      "type": "array",
                      "required": false,
                      "minItems": 1,
                      "items":{
                        "type": "string",
                        "minLength": 1
                      }
                    }
                  }
      },
      "arrayTodolist":{
        "type": "array",
        "items":{
            "$ref": "#/components/schemas/todolist"
        }
      }
        
      },
      "parameters": {
        "TodolistId":{
              "name": "todolistId",
              "in": "path",
              "required": true,
              "description": "Todolist for updated",
              "schema":{
                "type": "string"
              },
              "examples": {
                "java":{
                  "description": "sample todolist id for Java",
                  "value":"1"
                      },
                "php":{
                  "description": "example todolist id for php",
                  "value": 2
                }
              }
            }
      }
    }
  }